# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=None)),
                ('passport', models.BooleanField(default=None)),
                ('competition', models.BooleanField(default=None)),
                ('parent_competition', models.BooleanField(default=None)),
                ('breed', models.CharField(default=None, max_length=4)),
                ('sex', models.CharField(choices=[('male', 'мальчик'), ('female', 'девочка')], default=None, max_length=6)),
                ('city', models.CharField(default=None, max_length=100)),
                ('size', models.CharField(choices=[('small', 'маленький'), ('average', 'средний'), ('big', 'большой')], default=None, max_length=10)),
                ('price', models.IntegerField(default=None, max_length=100)),
                ('owner', models.CharField(choices=[('small', 'маленький'), ('average', 'средний'), ('big', 'большой')], default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=None)),
                ('passport', models.BooleanField(default=None)),
                ('competition', models.BooleanField(default=None)),
                ('parent_competition', models.BooleanField(default=None)),
                ('breed', models.CharField(default=None, max_length=4)),
                ('sex', models.CharField(choices=[('male', 'мальчик'), ('female', 'девочка')], default=None, max_length=6)),
                ('city', models.CharField(default=None, max_length=100)),
                ('size', models.CharField(choices=[('small', 'маленький'), ('average', 'средний'), ('big', 'большой')], default=None, max_length=10)),
                ('price', models.IntegerField(default=None, max_length=100)),
                ('owner', models.CharField(choices=[('small', 'маленький'), ('average', 'средний'), ('big', 'большой')], default=None, max_length=10)),
            ],
        ),
    ]
