# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180121_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='parent_competition',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='parent_competition',
        ),
    ]
