# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180121_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.IntegerField(default=8901),
        ),
    ]
