# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180122_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='info',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='info',
            name='location',
        ),
        migrations.AddField(
            model_name='info',
            name='who',
            field=models.CharField(choices=[('Заводчик', 'Заводчик'), ('Приют', 'Приют'), ('Пользователь', 'Пользователь')], default='Пользователь', max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='who', to=settings.AUTH_USER_MODEL),
        ),
    ]
