# Generated by Django 2.0.2 on 2018-03-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20180218_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='phone_number',
            field=models.CharField(default='-', max_length=13),
        ),
        migrations.AlterField(
            model_name='info',
            name='who',
            field=models.CharField(choices=[('Заводчик', 'Заводчик'), ('Приют', 'Приют'), ('Пользователь', 'Пользователь')], default='Частное лицо', max_length=30),
        ),
    ]
