# Generated by Django 2.0.2 on 2018-03-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20180314_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
