# Generated by Django 2.0.2 on 2018-03-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20180314_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='phone',
            field=models.CharField(default='?', max_length=20),
        ),
        migrations.AddField(
            model_name='dog',
            name='phone',
            field=models.CharField(default='?', max_length=20),
        ),
    ]
